package hello.springboot.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;

import hello.springboot.model.Evk_users;

public interface Evk_usersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    int insert(Evk_users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    int insertSelective(Evk_users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    Evk_users selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Evk_users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Evk_users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evk_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Evk_users record);

	List<Evk_users> selectAllEvk_users();
	
	@Select("SELECT UserID, UserSerial, Comments, Password, IsLockedOut FROM evk_users")
	List<Evk_users> getEvk_users();
}