#spring:
#  profiles:
#    active: dev
boot:
    name: 沉沉的
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: home.springboot.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
    
server:
  context-path: /spring
  port: 8080

spring:
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://192.168.1.77:13306/mytest?useUnicode=true&characterEncoding=utf-8
       username: root
       password: my-secret-pw
   devtools:
       restart:
          additional-paths: src/main/java
          enabled: true
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
