mybatis:
  mapperLocations: =classpath:mapper/*.xml
server:
  context-path: /spring
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/javatest?useSSL=false
    username: postgres
